QC_CATEGORY = "QC"
RENDER_SETTING_CATEGORY = 'QC Render Settings'
RENDERMESH_PARAMETER_CATEGORY = 'QC Mesh Parameter'
MODEL_PARAMETER_CATEGORY = 'QC Model Parameter'
MATERIAL_CATEGORY = 'QC Material'
ANIMATION_CATEGORY = 'QC Animation'